theme: jekyll-theme-hacker

title: The Azure DevOps PowerShell Module
description: PowerShell Module for interacting with Azure Dev Ops

url: https://utm-online.github.io/AzureDevOpsPsModule/

collections:
  docs:
    permalink: "/:collection/:path/"
    output: true

defaults:
  - scope:
      path: _docs
      type: docs
    values:
      layout: docs

plugins:
  - jekyll-sitemap

exclude:
  - .gitignore
  - LICENSE