theme: jekyll-theme-leap-day

title: The Azure DevOps PowerShell Module
description: PowerShell Module for interacting with Azure Dev Ops

plugins:
  - jekyll-sitemap

exclude:
  - .gitignore
  - LICENSE
