//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureDevOpsMgmt.CoreTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AzureDevOpsMgmt.CoreTests.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Id&quot;:  1041861,
        ///    &quot;Rev&quot;:  7,
        ///    &quot;Fields&quot;:  {
        ///                   &quot;System.AreaPath&quot;:  &quot;Enterprise Cloud\\Analytics and Tools&quot;,
        ///                   &quot;System.TeamProject&quot;:  &quot;Enterprise Cloud&quot;,
        ///                   &quot;System.IterationPath&quot;:  &quot;Enterprise Cloud\\CY19-H1\\CY19-Q1\\CY19-03&quot;,
        ///                   &quot;System.WorkItemType&quot;:  &quot;Task&quot;,
        ///                   &quot;System.State&quot;:  &quot;Active&quot;,
        ///                   &quot;System.Reason&quot;:  &quot;Work started&quot;,
        ///                   &quot;System.AssignedTo&quot;:  {
        ///                      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JsonPatchSideB {
            get {
                return ResourceManager.GetString("JsonPatchSideB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Id&quot;:  1041861,
        ///    &quot;Rev&quot;:  7,
        ///    &quot;Fields&quot;:  {
        ///                   &quot;System.AreaPath&quot;:  &quot;Enterprise Cloud\\Analytics and Tools&quot;,
        ///                   &quot;System.TeamProject&quot;:  &quot;Enterprise Cloud&quot;,
        ///                   &quot;System.IterationPath&quot;:  &quot;Enterprise Cloud\\CY19-H1\\CY19-Q1\\CY19-03&quot;,
        ///                   &quot;System.WorkItemType&quot;:  &quot;Task&quot;,
        ///                   &quot;System.State&quot;:  &quot;Active&quot;,
        ///                   &quot;System.Reason&quot;:  &quot;Work started&quot;,
        ///                   &quot;System.AssignedTo&quot;:  {
        ///                      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JsonPatchTestSideA {
            get {
                return ResourceManager.GetString("JsonPatchTestSideA", resourceCulture);
            }
        }
    }
}
